movieproject/movieapp/urls.py
from django.urls import path

from .import views
app_name='movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img= models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import movie


class movieform(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from.models import movie
from. forms import movieform
# Create your views here.
def index(request):
    movieobj=movie.objects.all()
    content={ 'movie_list':movieobj}
    return render(request,'index.html',content)
def detail(request,movie_id):
    m=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'moviel':m})
def add_movie(request):
    if request.method=="POST":
        name1=request.POST.get('name',)
        desc1=request.POST.get('desc',)
        year1=request.POST.get('year',)
        img1=request.FILES['img']
        movie1=movie(name=name1,desc=desc1,year=year1,img=img1)
        movie1.save()
    return render(request,'add.html')
def update(request,id):
    movie1=movie.objects.get(id=id)
    formv=movieform(request.POST or None,request.FILES,instance=movie1)
    if formv.is_valid():
        formv.save()
        return redirect('/')
    return render(request,'edit.html',{'form':formv,'movie':movie1})
def delete(request,id):
    if request.method=="POST":
        movie1=movie.objects.get(id=id)
        movie1.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html'%}
{% block body %}
<h1>ADD NEW MOVIE</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name"><br>
     <input type="text" name="desc" placeholder="Enter movie desc"><br>
     <input type="text" name="year" placeholder="Enter movie year"><br>
     <input type="file" name="img"><br>
     <input type="submit" >
</form>
{% endblock %}

movieproject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Movies</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">New movies</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">famous movies</a>
      </li>
    </ul>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure want to delete ?
    <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{moviel.img.url}}" width="300" height="500">
        </div>
        <div class="col-md-6">
            <h2>{{moviel.name}}</h2>
            <h5>{{moviel.desc}}</h5>
            <h6>{{moviel.year}}</h6>
            <a class="btn btn-warning" href="{% url 'movieapp:update' moviel.id %}">update</a>
            <a class="btn btn-warning" href="{% url 'movieapp:delete' moviel.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
<!--{% extends 'base.html'%}-->
<!--{% block body %}-->
<h1>EDIT MOVIE</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
<!--{% endblock %}-->

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div  class="container">
  <div class="row" style="margin:right">
    {% for i in movie_list %}
    <div class="col-md-3">
      <div class="card-deck">
      <div class="card" style="width: 18rem; " >
         <img  src="{{i.img.url}}" class="card-img-top" alt=""  height="250">
          <div class="card-body">
             <h5 class="card-title"> {{i.name}}</h5>
<!--              <p class="card-text">{{i.desc}}</p>-->
              <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
          </div>
      </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}